// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package database

import (
	"context"
)

const addIdentity = `-- name: AddIdentity :exec
INSERT INTO identity (
	address, key_bundle, net_addr_bundle_time, net_addr_bundle
) VALUES (
	?, ?, ?, ?
)
`

type AddIdentityParams struct {
	Address           string
	KeyBundle         string
	NetAddrBundleTime int64
	NetAddrBundle     string
}

func (q *Queries) AddIdentity(ctx context.Context, arg AddIdentityParams) error {
	_, err := q.db.ExecContext(ctx, addIdentity,
		arg.Address,
		arg.KeyBundle,
		arg.NetAddrBundleTime,
		arg.NetAddrBundle,
	)
	return err
}

const deleteIdentity = `-- name: DeleteIdentity :exec
DELETE FROM identity
WHERE address = ?
`

func (q *Queries) DeleteIdentity(ctx context.Context, address string) error {
	_, err := q.db.ExecContext(ctx, deleteIdentity, address)
	return err
}

const getIdentity = `-- name: GetIdentity :one
SELECT key_bundle, net_addr_bundle_time, net_addr_bundle
FROM identity
WHERE address = ?
`

type GetIdentityRow struct {
	KeyBundle         string
	NetAddrBundleTime int64
	NetAddrBundle     string
}

func (q *Queries) GetIdentity(ctx context.Context, address string) (GetIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentity, address)
	var i GetIdentityRow
	err := row.Scan(&i.KeyBundle, &i.NetAddrBundleTime, &i.NetAddrBundle)
	return i, err
}

const getIdentityId = `-- name: GetIdentityId :one
SELECT id
FROM identity
WHERE address = ?
`

func (q *Queries) GetIdentityId(ctx context.Context, address string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIdentityId, address)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRandomIdentities = `-- name: GetRandomIdentities :many
SELECT address, key_bundle, net_addr_bundle_time, net_addr_bundle
FROM identity
ORDER BY RANDOM() LIMIT ?
`

type GetRandomIdentitiesRow struct {
	Address           string
	KeyBundle         string
	NetAddrBundleTime int64
	NetAddrBundle     string
}

func (q *Queries) GetRandomIdentities(ctx context.Context, limit int64) ([]GetRandomIdentitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRandomIdentities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomIdentitiesRow
	for rows.Next() {
		var i GetRandomIdentitiesRow
		if err := rows.Scan(
			&i.Address,
			&i.KeyBundle,
			&i.NetAddrBundleTime,
			&i.NetAddrBundle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomIdentity = `-- name: GetRandomIdentity :one
SELECT address, key_bundle, net_addr_bundle_time, net_addr_bundle
FROM identity
ORDER BY RANDOM() LIMIT 1
`

type GetRandomIdentityRow struct {
	Address           string
	KeyBundle         string
	NetAddrBundleTime int64
	NetAddrBundle     string
}

func (q *Queries) GetRandomIdentity(ctx context.Context) (GetRandomIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomIdentity)
	var i GetRandomIdentityRow
	err := row.Scan(
		&i.Address,
		&i.KeyBundle,
		&i.NetAddrBundleTime,
		&i.NetAddrBundle,
	)
	return i, err
}

const updateIdentity = `-- name: UpdateIdentity :exec
UPDATE identity
SET net_addr_bundle_time = ?, net_addr_bundle = ?
WHERE address = ?
`

type UpdateIdentityParams struct {
	NetAddrBundleTime int64
	NetAddrBundle     string
	Address           string
}

func (q *Queries) UpdateIdentity(ctx context.Context, arg UpdateIdentityParams) error {
	_, err := q.db.ExecContext(ctx, updateIdentity, arg.NetAddrBundleTime, arg.NetAddrBundle, arg.Address)
	return err
}
