// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO messages(
	sender_id,
	receiver_id,
	time,
	contents
)
SELECT
	(SELECT id FROM identity WHERE identity.address = ?3),
	(SELECT id FROM identity WHERE identity.address = ?4),
	?,
	?
`

type AddMessageParams struct {
	SenderAddress   string
	ReceiverAddress string
	Time            int64
	Contents        string
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.ExecContext(ctx, addMessage,
		arg.SenderAddress,
		arg.ReceiverAddress,
		arg.Time,
		arg.Contents,
	)
	return err
}

const getMessages = `-- name: GetMessages :many
SELECT
	sender.address AS sender_address,
	receiver.address AS receiver_address,
	messages.time,
	messages.contents
FROM messages
JOIN identity sender ON messages.sender_id = sender.id
JOIN identity receiver ON messages.receiver_id = receiver.id
WHERE sender.address = ?1
OR receiver.address = ?1
ORDER BY messages.time ASC
`

type GetMessagesRow struct {
	SenderAddress   string
	ReceiverAddress string
	Time            int64
	Contents        string
}

func (q *Queries) GetMessages(ctx context.Context, address string) ([]GetMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessages, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.SenderAddress,
			&i.ReceiverAddress,
			&i.Time,
			&i.Contents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
