// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Identity struct {
	ID                int64
	Address           string
	KeyBundle         string
	NetAddrBundleTime int64
	NetAddrBundle     string
}

type Message struct {
	ID         int64
	SenderID   int64
	ReceiverID int64
	Time       int64
	Contents   string
}

type Session struct {
	ID                int64
	IdentityID        int64
	RootKey           string
	OurEphemeralKey   string
	TheirEphemeralKey string
	SendChainKey      string
	SendMsgCount      int64
	SendPrevMsgCount  int64
	RecvChainKey      string
	RecvMsgCount      int64
	RecvPrevMsgCount  int64
}
