// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Identity struct {
	ID                int64
	Address           string
	KeyBundle         string
	NetAddrBundleTime int64
	NetAddrBundle     string
}

type Message struct {
	ID         int64
	SenderID   int64
	ReceiverID int64
	Timestamp  int64
	Contents   string
}

type Session struct {
	ID                int64
	IdentityID        int64
	RootKey           string
	OurEphemeralKey   string
	TheirEphemeralKey string
	SendChainKey      sql.NullString
	SendMsgCount      sql.NullInt64
	SendPrevMsgCount  sql.NullInt64
	RecvChainKey      sql.NullString
	RecvMsgCount      sql.NullInt64
	RecvPrevMsgCount  sql.NullInt64
}
