// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Identity struct {
	ID                int64
	Address           string
	Keybundle         string
	Netaddrbundletime int64
	Netaddrbundle     string
}
