// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const addIdentity = `-- name: AddIdentity :exec
INSERT INTO identity (
	address, keyBundle, netAddrBundleTime, netAddrBundle
) VALUES (
	?, ?, ?, ?
)
`

type AddIdentityParams struct {
	Address           string
	Keybundle         string
	Netaddrbundletime int64
	Netaddrbundle     string
}

func (q *Queries) AddIdentity(ctx context.Context, arg AddIdentityParams) error {
	_, err := q.db.ExecContext(ctx, addIdentity,
		arg.Address,
		arg.Keybundle,
		arg.Netaddrbundletime,
		arg.Netaddrbundle,
	)
	return err
}

const getIdentity = `-- name: GetIdentity :one
SELECT keyBundle, netAddrBundleTime, netAddrBundle FROM identity
WHERE address = ? LIMIT 1
`

type GetIdentityRow struct {
	Keybundle         string
	Netaddrbundletime int64
	Netaddrbundle     string
}

func (q *Queries) GetIdentity(ctx context.Context, address string) (GetIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentity, address)
	var i GetIdentityRow
	err := row.Scan(&i.Keybundle, &i.Netaddrbundletime, &i.Netaddrbundle)
	return i, err
}

const getIdentityId = `-- name: GetIdentityId :one
SELECT id FROM identity
WHERE address = ? LIMIT 1
`

func (q *Queries) GetIdentityId(ctx context.Context, address string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIdentityId, address)
	var id int64
	err := row.Scan(&id)
	return id, err
}
