// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
)

const addSession = `-- name: AddSession :exec
INSERT INTO sessions(
	identity_id,
	root_key,
	our_ephemeral_key,
	their_ephemeral_key,
	send_chain_key,
	send_msg_count,
	send_prev_msg_count,
	recv_chain_key,
	recv_msg_count,
	recv_prev_msg_count
)
SELECT id, ?, ?, ?, ?, ?, ?, ?, ?, ?
FROM identity WHERE address = ?
`

type AddSessionParams struct {
	RootKey           string
	OurEphemeralKey   string
	TheirEphemeralKey string
	SendChainKey      string
	SendMsgCount      int64
	SendPrevMsgCount  int64
	RecvChainKey      string
	RecvMsgCount      int64
	RecvPrevMsgCount  int64
	Address           string
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) error {
	_, err := q.db.ExecContext(ctx, addSession,
		arg.RootKey,
		arg.OurEphemeralKey,
		arg.TheirEphemeralKey,
		arg.SendChainKey,
		arg.SendMsgCount,
		arg.SendPrevMsgCount,
		arg.RecvChainKey,
		arg.RecvMsgCount,
		arg.RecvPrevMsgCount,
		arg.Address,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE identity_id = (
	SELECT id FROM identity
	WHERE address = ?
)
`

func (q *Queries) DeleteSession(ctx context.Context, address string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, address)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
	sessions.root_key,
	sessions.our_ephemeral_key,
	sessions.their_ephemeral_key,
	sessions.send_chain_key,
	sessions.send_msg_count,
	sessions.send_prev_msg_count,
	sessions.recv_chain_key,
	sessions.recv_msg_count,
	sessions.recv_prev_msg_count
FROM identity JOIN sessions ON identity.id = sessions.identity_id
WHERE identity.address = ? LIMIT 1
`

type GetSessionRow struct {
	RootKey           string
	OurEphemeralKey   string
	TheirEphemeralKey string
	SendChainKey      string
	SendMsgCount      int64
	SendPrevMsgCount  int64
	RecvChainKey      string
	RecvMsgCount      int64
	RecvPrevMsgCount  int64
}

func (q *Queries) GetSession(ctx context.Context, address string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, address)
	var i GetSessionRow
	err := row.Scan(
		&i.RootKey,
		&i.OurEphemeralKey,
		&i.TheirEphemeralKey,
		&i.SendChainKey,
		&i.SendMsgCount,
		&i.SendPrevMsgCount,
		&i.RecvChainKey,
		&i.RecvMsgCount,
		&i.RecvPrevMsgCount,
	)
	return i, err
}

const updateSessionRatchet = `-- name: UpdateSessionRatchet :exec
UPDATE sessions
SET
	root_key = ?,
	our_ephemeral_key = ?,
	their_ephemeral_key = ?,
	send_chain_key = ?,
	send_msg_count = ?,
	send_prev_msg_count = ?,
	recv_chain_key = ?,
	recv_msg_count = ?,
	recv_prev_msg_count = ?
WHERE identity_id = (
	SELECT id
	FROM identity
	WHERE address = ?
)
`

type UpdateSessionRatchetParams struct {
	RootKey           string
	OurEphemeralKey   string
	TheirEphemeralKey string
	SendChainKey      string
	SendMsgCount      int64
	SendPrevMsgCount  int64
	RecvChainKey      string
	RecvMsgCount      int64
	RecvPrevMsgCount  int64
	Address           string
}

func (q *Queries) UpdateSessionRatchet(ctx context.Context, arg UpdateSessionRatchetParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionRatchet,
		arg.RootKey,
		arg.OurEphemeralKey,
		arg.TheirEphemeralKey,
		arg.SendChainKey,
		arg.SendMsgCount,
		arg.SendPrevMsgCount,
		arg.RecvChainKey,
		arg.RecvMsgCount,
		arg.RecvPrevMsgCount,
		arg.Address,
	)
	return err
}

const updateSessionRecv = `-- name: UpdateSessionRecv :exec
UPDATE sessions
SET recv_chain_key = ?, recv_msg_count = ?
WHERE identity_id = (
	SELECT id
	FROM identity
	WHERE address = ?
)
`

type UpdateSessionRecvParams struct {
	RecvChainKey string
	RecvMsgCount int64
	Address      string
}

func (q *Queries) UpdateSessionRecv(ctx context.Context, arg UpdateSessionRecvParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionRecv, arg.RecvChainKey, arg.RecvMsgCount, arg.Address)
	return err
}

const updateSessionSend = `-- name: UpdateSessionSend :exec
UPDATE sessions
SET send_chain_key = ?, send_msg_count = ?
WHERE identity_id = (
	SELECT id
	FROM identity
	WHERE address = ?
)
`

type UpdateSessionSendParams struct {
	SendChainKey string
	SendMsgCount int64
	Address      string
}

func (q *Queries) UpdateSessionSend(ctx context.Context, arg UpdateSessionSendParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionSend, arg.SendChainKey, arg.SendMsgCount, arg.Address)
	return err
}
